version: 2

run:
  timeout: 5m

issues:
  exclude-rules:
    - path: "test/util/fake\\.go"
      linters:
        - staticcheck
      text: "SA1019.*NewSimpleClientset"
    - path: "pkg/apis/scheduling/v1alpha1/types_test\\.go"
      linters:
        - staticcheck
      text: "QF1008"

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused

linters-settings:
    errcheck:
      check-type-assertions: true
      check-blank: true
    govet:
      enable-all: true
      disable:
        - fieldalignment
    staticcheck:
      checks: ["all"]
